//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exercise()
        {
            this.UserExerciseSchedules = new HashSet<UserExerciseSchedule>();
        }
    
        public string ExerciseID { get; set; }
        public byte[] ExerciseGIF { get; set; }
        public string MuscleGroup { get; set; }
        public string MusclePart { get; set; }
        public string ExerciseName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserExerciseSchedule> UserExerciseSchedules { get; set; }
    }
}
