//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExerciseSchedule
    {
        public string ExercisePlanID { get; set; }
        public string UserId { get; set; }
        public string ExerciseID { get; set; }
        public int Reps { get; set; }
        public int Sets { get; set; }
    
        public virtual Exercise Exercise { get; set; }
        public virtual User User { get; set; }
    }
}
