//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFoodSchedule
    {
        public string MealPlanId { get; set; }
        public string userId { get; set; }
        public string foodId { get; set; }
        public System.DateTime mealTime { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual User User { get; set; }
    }
}
